name: CI

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Python library
        working-directory: python-lib
        run: python -m pip install -e .[dev]

      - name: Configure
        run: cmake --preset gcc-default
      
      - name: Build
        run: cmake --build --preset build-gcc
      
      - name: Run tests
        run: ctest --preset test-gcc

  example_arduino:
    name: Example (Arduino)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:samd

      - name: Setup Python library
        working-directory: python-lib
        run: python -m pip install -e .[dev]

      - name: Generate code
        working-directory: examples/arduino
        run: python -m line_protocol.codegen network.json --node Arduino --output .

      - name: Build sketch
        working-directory: examples/arduino
        run: arduino-cli compile -b arduino:samd:arduino_zero_edbg --library ../..

  python_test:
    name: Python Test
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python library
        working-directory: python-lib
        run: python -m pip install -e .[dev]
      
      - name: Run tests
        working-directory: python-lib
        run: python -m pytest

      # TODO: results and coverage?
      
# TODO: linting?

  sphinx_docs:
    name: Documentation
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: Build documentation
        run: python -m sphinx -b html -E docs docs/_build

      # TODO: archive